services:
  front-end:
    tty: true
    restart: always
    build:
      context: front/.
      dockerfile: Dockerfile
      target: dev
 #  ports:
 #    - "5173:5173"
    depends_on:
      - api 
    environment:
      PORT: 5173
      BACKEND_URL: http://api:8000
      VITE_API_ENDPOINT: http://localhost:8000
    network_mode: service:api
    volumes:
      - ./front/src:/app/src
      - ./front/svelte.config.js:/app/svelte.config.js
      - ./front/tailwind.config.js:/app/tailwind.config.js
      - ./front/tsconfig.json:/app/tsconfig.json
      - ./front/postcss.config.js:/app/postcss.config.js
        
  api:
    tty: true
    restart: always
    build:
      context: back/api/.
      dockerfile: Dockerfile
      target: dev
    ports:
      - "8000:8000"
      - "5173:5173"
      - "5432:5432"
    environment:
      PORT: 8000
      POSTGRES_CONNECTION_STRING: ${DATABASE_URL}
      OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}
      OAUTH_CLIENT_SECRET: ${OAUTH_CLIENT_SECRET}
      OAUTH_REDIRECT_URL: http://localhost:5173/auth/callback
      FIREBASE_API_KEY: ${FIREBASE_API_KEY}
      FIREBASE_AUTH_DOMAIN: ${FIREBASE_AUTH_DOMAIN}
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      FIREBASE_STORAGE_BUCKET: ${FIREBASE_STORAGE_BUCKET}
      FIREBASE_MESSAGING_SENDER_ID: ${FIREBASE_MESSAGING_SENDER_ID}
      FIREBASE_APP_ID: ${FIREBASE_APP_ID}
      RUST_BACKTRACE: 1
    volumes:
      - ./back/api/src:/usr/src/app/src

# DB
  postgres:
    image: postgres:12
    volumes:
      - postgres-data:/data/db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: 
 #  ports:
 #    - "5432:5432"
    network_mode: service:api

volumes:
  postgres-data:
networks:
  default:
    driver: bridge
